export const ROUTE_SEGMENTS = {
  accessControl: "access-control",
  auth: "auth",
  chat: "chat",
  documents: "documents",
  health: "health",
  knowledge: "knowledge",
  login: "login",
  logs: "logs",
  models: "models",
  notifications: "notifications",
  profile: "profile",
  processing: "processing",
  quality: "quality",
  settings: "settings",
  tickets: "tickets",
  users: "users",
} as const

export const ROUTES = {
  admin: "/admin",
  adminAccessControl: "/admin/access-control",
  adminDocuments: "/admin/documents",
  adminHealth: "/admin/health",
  adminLogs: "/admin/logs",
  adminModels: "/admin/models",
  adminSettings: "/admin/settings",
  adminUsers: "/admin/users",
  chat: "/chat",
  home: "/",
  ingester: "/ingester",
  ingesterDocuments: "/ingester/documents",
  ingesterProcessing: "/ingester/processing",
  ingesterQuality: "/ingester/quality",
  ingesterSettings: "/ingester/settings",
  knowledge: "/knowledge",
  legacySignIn: "/auth/login",
  login: "/login",
  notifications: "/notifications",
  profile: "/profile",
  signIn: "/login",
  tickets: "/tickets",
} as const

export type RouteKey = keyof typeof ROUTES
