export const ROUTE_SEGMENTS = {
  auth: "auth",
  chat: "chat",
  knowledge: "knowledge",
  login: "login",
  notifications: "notifications",
  profile: "profile",
  register: "register",
  tickets: "tickets",
} as const

export const ROUTES = {
  admin: "/admin",
  adminDocuments: "/admin/documents",
  adminHealth: "/admin/health",
  adminLogs: "/admin/logs",
  adminModels: "/admin/models",
  adminSettings: "/admin/settings",
  adminUsers: "/admin/users",
  chat: "/chat",
  home: "/",
  ingester: "/ingester",
  ingesterDocuments: "/ingester/documents",
  ingesterProcessing: "/ingester/processing",
  ingesterQuality: "/ingester/quality",
  ingesterSettings: "/ingester/settings",
  knowledge: "/knowledge",
  legacySignIn: "/auth/login",
  legacySignUp: "/auth/register",
  login: "/login",
  notifications: "/notifications",
  profile: "/profile",
  register: "/register",
  signIn: "/login",
  signUp: "/register",
  tickets: "/tickets",
} as const
